# ref. https://goreleaser.com/customization/build/
builds:
  - id: blob-cli
    main: ./cmd/blob-cli
    binary: blob-cli
    flags:
      - -v
    # TODO: remove this once we support 32-bit in avalanchego
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: freebsd
        goarch: 386
  - id: blobvm
    main: ./cmd/blobvm
    binary: blobvm
    flags:
      - -v
    # TODO: remove this once we support 32-bit in avalanchego
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: freebsd
        goarch: 386

release:
  github:
    owner: ava-labs
    name: blobvm
